### ISSUE TITLE
로컬 개발 환경 설정 - 도커

### ISSUE THREAD

**Issue by gdtknight** [JoberChipFrappuccino/joberchip-be-demo#5]
## 설정 내용

- `프로젝트루트/docker/mysql/compose.yml`

```yaml
version: '1'

services:
  mysql:
    container_name: joberchip_mysql
    image: mysql/mysql-server:latest
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - ${DB_PORT}:3306
    command:
      - 'mysqld'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
```

- `compose.yml` 이 위치한 디렉토리에 `.env` 파일 직접 생성. 아래 파일 내용은 예시

```yaml
DB_URL=localhost
DB_USER=joberdbusername
DB_PASSWORD=joberdbpassword
DB_NAME=joberchipDB
DB_PORT=3322
DB_DRIVER=com.mysql.cj.jdbc.Driver
```

## 실행

- Linux / macOS

```bash
$ docker compose up -d
```

- Windows

```cmd
c:\\프로젝트루트\docker\mysql> docker compose up -d
```
